### ISSUE TITLE
SOLID LOGIN MILESTONE 3: Authenticate only for now

### ISSUE THREAD

**Issue by gjwgit** [anusii/solid#11]
# Description

A sub-task of https://github.com/anusii/solid/issues/1

Implement the login GUI in `solid:solid_login.dart`. It should include:

- [x] image (default is the photo used in the INDI app)
- [x] logo (default is the logo used in the IND app)
- [x] title (default is 'LOGIN WITH YOUR POD')
- [x] URI (default is https://pods.solidcommunity.au)
- [x] GET POD button (default colour is as in podnotes)
- [x] LOGIN button (default colour is as in podnotes)
- [x] Link (default is https://solidporoject.org)
- [x] Version (obtained from pubspec.yaml)

- [x] For each of these that have a default there should be a class parameter to change them for the particular app. #16

Authentication is undertaken against the solid server listed in the URI.

When authenticated successfully, display the supplied widget.

**Do not check for the existence of the app data folder yet.** That will be milestone 4.

 If authorization fails after NN seconds return to the login page with a message that the authentication timed out or was cancelled. Discuss with Anushka for some way to return if the authentication is cancelled? Currently the app seems to wait forever. This might be worth a separate issue.

**Comment by gjwgit** [comment]
I've progressed with the required style for the implementation - avoid copy and paste, but instead re-engineer as you copy. The aim is for every segment of the code can be easily understood and comprehended. No more putting everything into one massive return!

**Comment by gjwgit** [comment]
![Image](https://github.com/anusii/solid/assets/1681429/b221fe2e-c3cd-4b3b-b54c-5187d10d26ca)

**Comment by gjwgit** [comment]
- [ ] Need to migrate required solid_auth code into solid.

**Comment by gjwgit** [comment]
Closing now. We won;t migrate solid_auth for now. Retain it and work to clean it up.
